"""followers

Revision ID: 212aeec9c308
Revises: f5cbfeebe0fc
Create Date: 2020-04-24 16:53:39.177748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212aeec9c308'
down_revision = 'f5cbfeebe0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
